# Generated by Django 3.0.3 on 2020-02-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='AuthorName')),
                ('age', models.SmallIntegerField(default=0, verbose_name='AuthorAge')),
                ('desc', models.TextField(default=0, verbose_name='AuthorAge')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='BookTitle')),
                ('url', models.CharField(blank=True, default='', max_length=256, verbose_name='BookUrl')),
                ('ctype', models.SmallIntegerField(choices=[(0, '英语书'), (1, '小黄书')], default=0, verbose_name='BookType')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('author', models.ManyToManyField(to='app.Author')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
                'db_table': 'book',
            },
        ),
    ]
